[book]
title = "High-throughput UDP with udipe"
authors = ["Hadrien Grasland"]
language = "en"
src = "src"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/HadrienG2/udipe/"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/HadrienG2/udipe/-/edit/main/doc/{path}"

